import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Common/System/system_stm32mp1xx.c
''')

src += Glob('drv_timer.c')

if GetDepend(['BSP_USING_GBE']):
    src += Glob('ports/eth/drv_eth.c')

path =  [cwd]
path += [cwd + '/CubeMX_Config/CM4/Inc']
path += [cwd + '/ports']

if GetDepend(['BSP_USING_GBE']):
    path += [cwd + '/ports/eth']

CPPDEFINES = ['CORE_CA7','STM32MP157Dxx']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
