# from building import *

# cwd  = GetCurrentDir()
# src  = Glob('*.c')
# list = os.listdir(cwd)
# CPPPATH = [cwd]
# objs = []

# if not GetDepend('BSP_DRV_EMAC'):
#     SrcRemove(src, ['drv_smc911x.c'])

# if not GetDepend('BSP_DRV_CLCD'):
#     SrcRemove(src, ['drv_clcd.c'])

# group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

# for d in list:
#     path = os.path.join(cwd, d)
#     if os.path.isfile(os.path.join(path, 'SConscript')):
#         objs = objs + SConscript(os.path.join(d, 'SConscript'))
# objs = objs + group

# Return('objs')

import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Common/System/system_stm32mp1xx.c
''')

src += Glob('drv_timer.c')

path =  [cwd]
path += [cwd + '/CubeMX_Config/CM4/Inc']
path += [cwd + '/ports']

CPPDEFINES = ['CORE_CA7','STM32MP157Dxx']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
